server:
    port:3000
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        # serviceUrl:
        #   defaultZone=http://localhost:8762/eureka