server:
  port: 3000
    
spring:
  application:
    name: a-bootiful-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password:
    initialization-mode: ALWAYS
    schema: classpath:schema.sql
    data: classpath:data.sql
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    open-in-view: false
    
      
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     serviceUrl:
#       defaultZone: http://localhost:8762/eureka
          
# logging:
#   level:
#     com:
#       netflix: DEBUG