server:
  port: 3001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password:
    main:
      allow-bean-definition-overriding: true
    jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: none
      open-in-view: false
